apps:
  - app_class: "steam_app_1974050" # Torchlight
    remaps:
      - key: e        # pressing e...
        to: [q, e] # ...also presses q, w, and e
        delay: 50     # optional: ms between each mapped key (default 50)
